name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          latexmk_use_xelatex: true
          root_file: |
            *.tex
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: pdf-files
          path: |
            *.pdf
      - name: Generate release tag
        id: generate_release_tag
        uses: alexvingg/next-release-tag@v1.0.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ''   
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.generate_release_tag.outputs.release_tag }}
          name: Release ${{ steps.generate_release_tag.outputs.release_tag }}
          files: |
            *.pdf
